# a = int(input("vvedite chislo"))
# print(a,a*2)
# a = 46
# b = 6
# print(a,b*5)
# a = (5,"F","Привет",90.2)
# b = ("67")
# frozenset(b)
# print(a[2])
# a = (input("vvedite 4 znacnoe chislo"))
# b = list(a)
# for i in b:
#     print(i)
# a = input("vawe imya")
# b = input("vawa familiya")
# c = input("skolko vam let")
# print(a,b,c)
# a = int(input("vvedite 1 chislo"))
# b = int(input("vvedite 2 chislo"))
# c = int(input("vvedite 3 chislo"))
# print(a+b+c)
# print(a+b-c)
# print(a-b-c)
# a = int(input("vvedite 1 chislo"))
# b = float(input("vvedite 2 chislo"))
# c = input("vvedite 3 chislo")
# print(a,b,c)
a = int(input("vvedite 1 chislo"))
b = int(input("vvedite 2 chislo"))
c = int(input("vvedite 3 chislo"))
print(a+b+c)